// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaoefidvihsmqptmcjqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhb2VmaWR2aWhzbXFwdG1janFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTY2NjMsImV4cCI6MjA1NzQzMjY2M30.AaYLCFK3QaHjukRslA_hZZEcPuUgReSLqhofPL-yhFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);